services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@pg:5432/app_db
      SECRET_KEY: your-secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app_user", "-d", "app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg-data:
