name: Check Commit

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: pipx install poetry

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run lints
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-22.04
    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@127.0.0.1:5432/fast_zero
    services:
      pg:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fast_zero
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: pipx install poetry

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run tests
        run: make test
